
# 环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 9081
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100
# 日志配置
logging:
  level:
    com.zw: info
    org.springframework: warn

#iotdb配置
iotdb:
#  host: 10.168.136.130
#  host: 127.0.0.1
#  host: 192.168.1.34
  host: 192.168.1.39
  port: 6667
  user: "root"
  password: "root"

#iotdb性能测试配置
iotdbTest:
  #测试写入多少轮
  writeWheel: 10
  #每轮总写入条多少数据
  allWriteRowNum: 100000
  #测试写入时是否启用批量写,1启用,0:不启用(单条写入)
  openBatchWrite: 0
  #一个批写入多少条数据 默认1000
  batchWriteRowNum: 1000





