
# 环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 9081
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100
# 日志配置
logging:
  level:
    com.zw: info
    org.springframework: warn

#iotdb配置
iotdb:
  host: 127.0.0.1
  port: 6667
  user: "root"
  password: "root"



